http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        xssProtection: true
        referrerPolicy: no-referrer-when-downgrade
        customResponseHeaders:
          X-Powered-By: ""
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
    gzip-compress:
      compress: {}
